check build process

diff --git a/.github/workflows/edgeDevicePush.yml b/.github/workflows/edgeDevicePush.yml
--- a/.github/workflows/edgeDevicePush.yml
+++ b/.github/workflows/edgeDevicePush.yml
@@ -1,4 +1,4 @@
-name: fNIRS Edge Device Deployment
+name: fNIRS Edge Device Update
 
 on:
   workflow_dispatch:
@@ -6,7 +6,7 @@ on:
     branches: [ "fnirs-edge" ]
 
 jobs:
-  Edge-Device-1:
+  Edge-Device-Update:
     runs-on: ubuntu-latest
     steps:
 
@@ -20,32 +20,64 @@ jobs:
       with:
         network_id: ${{ secrets.ZEROTIER_NETWORK }}
         auth_token: ${{ secrets.ZEROTIER_TOKEN }}
-    
+
     - name: Check ZeroTier Host Connectivity
       shell: bash
       run: |
         count=5
-        while ! ping -c 1 ${{ secrets.EDGE_DEVICE_1_ZEROTIER_IP }} ; do
+        while ! ping -c 1 ${{ secrets.GOOGLE_VM_ZEROTIER_IP }} ; do
           echo "waiting..." ;
           sleep 1 ;
           let count=count-1
         done
         echo "ZeroTier Host Available"
     
-    - name: Generating SSH Key
-      run: echo "${{ secrets.EDGE_DEVICE_1_FNIRS_KEY }}" > ./tempKey
-    
-    - name: Setting Permission to SSH Key
-      run: chmod 600 ./tempKey
-    
-    - name: Transferring Payload
+    - name: Setup Node & NPM
+      uses: actions/setup-node@v4
+      with:
+        node-version: 20.x
+
+    - name: Build Captive Portal
       shell: bash
-      run: |
-        scp -o "StrictHostKeyChecking no" -i ./tempKey -r ../fNIRS-BloodVitals ${{ secrets.EDGE_DEVICE_1_USER }}@${{ secrets.EDGE_DEVICE_1_ZEROTIER_IP }}:/home/${{ secrets.EDGE_DEVICE_1_USER }}/
+      run:  |
+        cd ./frontend
+        npm install
+        npm run buil
+        mv ./dist ../
+        cd ../
+        ls -lah ./dist
+
+    # - name: ZeroTier Login
+    #   uses: zerotier/github-action@v1
+    #   with:
+    #     network_id: ${{ secrets.ZEROTIER_NETWORK }}
+    #     auth_token: ${{ secrets.ZEROTIER_TOKEN }}
     
-    - name: Payload Deployment
-      run: ssh -o "StrictHostKeyChecking no" -i ./tempKey ${{ secrets.EDGE_DEVICE_1_USER }}@${{ secrets.EDGE_DEVICE_1_ZEROTIER_IP }} /bin/bash ./fNIRS-BloodVitals/deployment.sh
+    # - name: Check ZeroTier Host Connectivity
+    #   shell: bash
+    #   run: |
+    #     count=5
+    #     while ! ping -c 1 ${{ secrets.EDGE_DEVICE_1_ZEROTIER_IP }} ; do
+    #       echo "waiting..." ;
+    #       sleep 1 ;
+    #       let count=count-1
+    #     done
+    #     echo "ZeroTier Host Available"
     
-    - name: Payload Cleanup
-      run: ssh -o "StrictHostKeyChecking no" -i ./tempKey ${{ secrets.EDGE_DEVICE_1_USER }}@${{ secrets.EDGE_DEVICE_1_ZEROTIER_IP }} rm -r ./fNIRS-BloodVitals
+    # - name: Generating SSH Key
+    #   run: echo "${{ secrets.EDGE_DEVICE_1_FNIRS_KEY }}" > ./tempKey
+    
+    # - name: Setting Permission to SSH Key
+    #   run: chmod 600 ./tempKey
+    
+    # - name: Transferring Payload
+    #   shell: bash
+    #   run: |
+    #     scp -o "StrictHostKeyChecking no" -i ./tempKey -r ../fNIRS-BloodVitals ${{ secrets.EDGE_DEVICE_1_USER }}@${{ secrets.EDGE_DEVICE_1_ZEROTIER_IP }}:/home/${{ secrets.EDGE_DEVICE_1_USER }}/
+    
+    # - name: Payload Deployment
+    #   run: ssh -o "StrictHostKeyChecking no" -i ./tempKey ${{ secrets.EDGE_DEVICE_1_USER }}@${{ secrets.EDGE_DEVICE_1_ZEROTIER_IP }} /bin/bash ./fNIRS-BloodVitals/deployment.sh
+    
+    # - name: Payload Cleanup
+    #   run: ssh -o "StrictHostKeyChecking no" -i ./tempKey ${{ secrets.EDGE_DEVICE_1_USER }}@${{ secrets.EDGE_DEVICE_1_ZEROTIER_IP }} rm -r ./fNIRS-BloodVitals
       
